version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    environment:
      PYTHONPATH: /workspace/src
      QDRANT_HOST: qdrant
      QDRANT_PORT: "6333"
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    command: ["sh", "-c", "sleep infinity"]  # <-- keep container running
